
export const incrementcounter="incrementcounter"//4
export const decrementcounter="decrementcounter"
export const GETDATAFIERCATEGORY="GETDATAFIERCATEGORY"
export const ADD_FIERCATEGORY = "ADD_FIERCATEGORY";
export const DELETE_FIERCATEGORY = "DELETE_FIERCATEGORY";
export const UPDATE_FIERCATEGORY = "UPDATE_FIERCATEGORY";
export const ADDSUBCATEGORYDATA = "ADDSUBCATEGORYDATA";
export const DELETESUBCATEGORYDATA = "DELETESUBCATEGORYDATA";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";

export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
